server:
  port: 80
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabse
    username: root
    password: AlonaGM26
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        show_sql: true

logging:
  file:
    name: logs/app.log